CREATE TABLE encuestas( id INTEGER AUTO_INCREMENT,
                       nombre VARCHAR(20) NOT NULL,
                       apellidos VARCHAR(40) NOT NULL,
                       email VARCHAR(100) NOT NULL,
                       fecha_nacimiento DATE,
                       sexo CHAR(1),
                       aficiones VARCHAR(75),
                       estudios VARCHAR(20),
                       observaciones TEXT,
                       foto VARCHAR(100),
                       created_at DATETIME NOT NULL,
                       updated_at DATETIME NOT NULL,
                       PRIMARY KEY (id),
                       CONSTRAINT UQ_email UNIQUE (email));